# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6a5d3d488a43c5fac33905558d026fea"
name = "merchantfix"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
